version: '3.8'

services:
  # Servidor Laravel (Nginx + PHP)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soccto_app
    restart: unless-stopped
    ports:
      - "5061:80"
    environment:
      APP_URL: "http://soccto.seroficom.com:5061"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - apps-network

  # Base de Datos MySQL
  mysql:
    image: 'mysql:8.0'
    container_name: soccto_db
    restart: unless-stopped
    ports:
      - "5064:3306" # <--- Cambiado a 5064 externo
    environment:
      MYSQL_ROOT_PASSWORD: "Soccto789!#"
      MYSQL_DATABASE: "soccto_db"
      MYSQL_USER: "soccto_admin"
      MYSQL_PASSWORD: "Soccto789!#"
    volumes:
      - soccto_db_data:/var/lib/mysql
    networks:
      - apps-network

  # phpMyAdmin
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: soccto_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "5062:80"
    environment:
      PMA_HOST: soccto_db # ConexiÃ³n interna por nombre de contenedor
      PMA_PORT: 3306      # Internamente MySQL siempre escucha en 3306
    networks:
      - apps-network

networks:
  apps-network:
    external: true

volumes:
  soccto_db_data:
    driver: local