version: '3.8'

services:
  # Servidor Laravel con APACHE
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soccto_app
    restart: unless-stopped
    ports:
      - "5061:80" # Mantenemos el 5061 (Cuidado con el bloqueo del navegador)
    environment:
      APP_URL: "http://soccto.seroficom.com:5061"
    volumes:
      - ./backend:/var/www/html
    networks:
      - apps-network

  # Base de Datos MySQL
  mysql:
    image: 'mysql:8.0'
    container_name: soccto_db
    restart: unless-stopped
    ports:
      - "5064:3306" # Puerto solicitado 5064
    environment:
      MYSQL_ROOT_PASSWORD: "Soccto789!#"
      MYSQL_DATABASE: "soccto_db"
      MYSQL_USER: "soccto_admin"
      MYSQL_PASSWORD: "Soccto789!#"
    volumes:
      - soccto_db_data:/var/lib/mysql
    networks:
      - apps-network

  # phpMyAdmin
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: soccto_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "5062:80"
    environment:
      PMA_HOST: soccto_db
      PMA_PORT: 3306
    networks:
      - apps-network

networks:
  apps-network:
    external: true # Usa la red existente

volumes:
  soccto_db_data:
    driver: local