version: '3.8'

services:
  # Aplicativo Laravel
  app_soccto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_soccto
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - soccto_network

  # Servidor Web (Nginx)
  web_soccto:
    image: nginx:alpine
    container_name: 80VS_soccto
    restart: unless-stopped
    ports:
      - "5782:5782"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - soccto_network
    depends_on:
      - app_soccto

networks:
  soccto_network:
    driver: bridge