version: '3.8'

services:
  # Servidor Laravel (PHP + Nginx)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soccto_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_URL: "http://soccto.seroficom.com:5061"
    ports:
      - '5061:80'
    volumes:
      - '.:/var/www/html'
      # Mapeamos tu archivo de configuración de nginx
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - apps-network

  # Base de Datos MySQL
  mysql:
    image: 'mysql:8.0'
    container_name: soccto_db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'soccto_db_data:/var/lib/mysql'
    networks:
      - apps-network

  # phpMyAdmin
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: soccto_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '5062:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      # Esto ayuda si tienes bases de datos grandes
      UPLOAD_LIMIT: 64M
    networks:
      - apps-network

# Configuración de Redes y Volúmenes
networks:
  apps-network:
    external: true # Usa la red existente que mostraste en tu captura

volumes:
  soccto_db_data:
    driver: local