version: '3.8'

services:
  # Base de Datos MySQL
  db_soccto:
    image: mysql:8.0
    container_name: mysql_db_soccto
    restart: always
    environment:
      MYSQL_DATABASE: soccto_db
      MYSQL_USER: soccto_admin
      MYSQL_PASSWORD: Soccto789!#
      MYSQL_ROOT_PASSWORD: RootSoccto2024!#
    volumes:
      - db_data_soccto:/var/lib/mysql
    networks:
      - soccto_net

  # phpMyAdmin (Puerto 5882 para no chocar con el otro app)
  phpmyadmin_soccto:
    image: phpmyadmin:latest
    container_name: phpmyadmin_soccto_service
    restart: always
    ports:
      - "5882:80"
    environment:
      - PMA_HOST=db_soccto
    depends_on:
      - db_soccto
    networks:
      - soccto_net

  # Laravel App (Backend)
  app_backend:
    build:
      context: ./backend      # <--- AQUÍ: Indica la carpeta
      dockerfile: Dockerfile  # <--- AQUÍ: El nombre del archivo dentro de esa carpeta
    container_name: laravel_api_soccto
    restart: always
    volumes:
      - ./backend:/var/www
    depends_on:
      - db_soccto
    networks:
      - soccto_net

  # Nginx (Puerto 5881 para no chocar con el otro app)
  web_backend:
    image: nginx:alpine
    container_name: 80VS_soccto
    restart: always
    ports:
      - "5881:5881"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_backend
    networks:
      - soccto_net

networks:
  soccto_net:
    driver: bridge

volumes:
  db_data_soccto: