version: '3.8'

services:
  # 1. Base de Datos MySQL
  db_soccto:
    image: mysql:8.0
    container_name: mysql_db_soccto
    restart: always
    environment:
      MYSQL_DATABASE: soccto_db
      MYSQL_USER: soccto_admin
      MYSQL_PASSWORD: Soccto789!#
      MYSQL_ROOT_PASSWORD: RootSoccto2024!#
    ports:
      - "33060:3306" # Puerto para conectar desde tu PC (Workbench/DBeaver)
    volumes:
      - db_data_soccto:/var/lib/mysql
    networks:
      - apps-network

  # 2. phpMyAdmin (Puerto 5062)
  phpmyadmin_soccto:
    image: phpmyadmin:latest
    container_name: phpmyadmin_soccto_service
    restart: always
    ports:
      - "5062:80"
    environment:
      - PMA_HOST=db_soccto
    depends_on:
      - db_soccto
    networks:
      - apps-network

  # 3. Laravel App (Backend - PHP-FPM)
  app_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_api_soccto
    restart: always
    volumes:
      - ./backend:/var/www
    depends_on:
      - db_soccto
    networks:
      - apps-network

  # 4. Nginx (Servidor Web para el Backend - Puerto 5061)
  web_backend:
    image: nginx:alpine
    container_name: nginx_backend_soccto
    restart: always
    ports:
      - "5061:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_backend
    networks:
      - apps-network

  # 5. Frontend (Reserva de espacio - Puerto 5060)
  # frontend_soccto:
  #   image: nginx:alpine # O la imagen que vayas a usar
  #   container_name: frontend_soccto
  #   ports:
  #     - "5060:80"
  #   networks:
  #     - apps-network

networks:
  apps-network:
    external: true # <--- ESTO ES CLAVE: Indica que la red ya existe en Portainer

volumes:
  db_data_soccto: