version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soccto_app
    restart: unless-stopped
    ports:
      - "5061:80" # Mapeo al puerto 5061 solicitado
    environment:
      APP_URL: "http://soccto.seroficom.com:5061"
    volumes:
      # Sincroniza la carpeta local 'backend' con el destino en el contenedor
      - ./backend:/var/www/html 
    networks:
      - apps-network

  mysql:
    image: 'mysql:8.0'
    container_name: soccto_db
    restart: unless-stopped
    ports:
      - "5064:3306" # Puerto solicitado 5064 para MySQL
    environment:
      MYSQL_ROOT_PASSWORD: "Soccto789!#"
      MYSQL_DATABASE: "soccto_db"
      MYSQL_USER: "soccto_admin"
      MYSQL_PASSWORD: "Soccto789!#"
    volumes:
      - soccto_db_data:/var/lib/mysql
    networks:
      - apps-network

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: soccto_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "5062:80" # Puerto solicitado 5062 para phpMyAdmin
    environment:
      PMA_HOST: soccto_db
      PMA_PORT: 3306
    networks:
      - apps-network

networks:
  apps-network:
    external: true # Usa la red bridge 172.18.0.1 existente

volumes:
  soccto_db_data:
    driver: local