version: '3.8'

services:
  db_soccto:
    image: mysql:8.0
    container_name: mysql_db_soccto
    restart: always
    environment:
      MYSQL_DATABASE: soccto_db
      MYSQL_USER: soccto_admin
      MYSQL_PASSWORD: "Soccto789!#"
      MYSQL_ROOT_PASSWORD: "RootSoccto2024!#"
    ports:
      - "33060:3306"
    volumes:
      - db_data_soccto:/var/lib/mysql
    networks:
      - apps-network

  app_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_api_soccto
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db_soccto
      DB_PORT: 3306
      DB_DATABASE: soccto_db
      DB_USERNAME: soccto_admin
      DB_PASSWORD: "Soccto789!#"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db_soccto
    networks:
      - apps-network

  web_backend:
    image: nginx:alpine
    container_name: nginx_backend_soccto
    restart: always
    ports:
      - "5061:80"
    volumes:
      - ./backend:/var/www
      # Ruta verificada seg√∫n tu imagen de VS Code
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app_backend
    networks:
      - apps-network

networks:
  apps-network:
    external: true

volumes:
  db_data_soccto: