version: '3.8'

services:
  # Aplicación Laravel
  app:
    build:
      context: ./backend # <--- IMPORTANTE: Aquí le decimos que entre a la carpeta backend
      dockerfile: Dockerfile
    container_name: soccto_app
    restart: unless-stopped
    environment:
      APP_URL: "http://soccto.seroficom.com:5061"
    ports:
      - "5061:80"
    volumes:
      - ./backend:/var/www/html # Ajustamos el volumen a la carpeta backend
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - apps-network

  # Base de Datos MySQL
  mysql:
    image: 'mysql:8.0'
    container_name: soccto_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_DATABASE:-soccto_db}
    volumes:
      - soccto_db_data:/var/lib/mysql
    networks:
      - apps-network

  # phpMyAdmin
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: soccto_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "5062:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - apps-network

networks:
  apps-network:
    external: true # Usa la red bridge 172.18.0.0/16 de tu imagen

volumes:
  soccto_db_data:
    driver: local