version: '3.8'

services:
  # Base de Datos MySQL
  db_soccto:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: soccto_db
      MYSQL_USER: soccto_admin
      MYSQL_PASSWORD: Soccto789!#
      MYSQL_ROOT_PASSWORD: RootSoccto2024!#
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - soccto_net

  # phpMyAdmin (Acceso puerto 5782)
  phpmyadmin_soccto:
    image: phpmyadmin:latest
    container_name: phpmyadmin_service
    restart: always
    ports:
      - "5783:80" # Cambiamos el puerto externo a 5783
    environment:
      - PMA_HOST=db_soccto
    depends_on:
      - db_soccto
    networks:
      - soccto_net

  # Laravel App (Backend)
  app_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: always
    volumes:
      - ./backend:/var/www
    depends_on:
      - db_soccto
    networks:
      - soccto_net

  # Nginx (Acceso puerto 5781)
  web_backend:
    image: nginx:alpine
    container_name: 80VS_soccto
    restart: always
    ports:
      - "5781:5781"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_backend
    networks:
      - soccto_net

networks:
  soccto_net:
    driver: bridge

volumes:
  db_data: