version: '3.9' # Subimos a 3.9 para soportar configs inline de forma estable

services:
  # 1. Base de Datos MySQL (Interno 3306)
  db_soccto:
    image: mysql:8.0
    container_name: mysql_db_soccto
    restart: always
    environment:
      MYSQL_DATABASE: soccto_db
      MYSQL_USER: soccto_admin
      MYSQL_PASSWORD: Soccto789!#
      MYSQL_ROOT_PASSWORD: RootSoccto2024!#
    ports:
      - "5065:3306" # Mapeamos MySQL al final del rango (5065) para acceso externo
    volumes:
      - db_data_soccto:/var/lib/mysql
    networks:
      - apps-network

  # 2. phpMyAdmin (Puerto 5063)
  phpmyadmin_soccto:
    image: phpmyadmin:latest
    container_name: phpmyadmin_soccto_service
    restart: always
    ports:
      - "5063:80"
    environment:
      - PMA_HOST=db_soccto
    depends_on:
      - db_soccto
    networks:
      - apps-network

  # 3. Laravel App (PHP-FPM)
  app_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_api_soccto
    restart: always
    volumes:
      - ./backend:/var/www
    depends_on:
      - db_soccto
    networks:
      - apps-network

  # 4. Nginx (Servidor Web Backend - Puerto 5062)
  web_backend:
    image: nginx:alpine
    container_name: nginx_backend_soccto
    restart: always
    ports:
      - "5062:80" # Tu API/Backend ahora en el 5062
    volumes:
      - ./backend:/var/www
      - nginx_config:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app_backend
    networks:
      - apps-network

# Configuraci√≥n de Nginx inyectada directamente (Evita errores de carpeta/archivo)
configs:
  nginx_config:
    inline: |
      server {
          listen 80;
          server_name soccto.seroficom.com;
          index index.php index.html;
          root /var/www/public;

          location ~ \.php$ {
              try_files $$uri =404;
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass app_backend:9000;
              fastcgi_index index.php;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $$document_root$$fastcgi_script_name;
              fastcgi_param PATH_INFO $$fastcgi_path_info;
          }

          location / {
              try_files $$uri $$uri/ /index.php?$$query_string;
              gzip_static on;
          }
      }

networks:
  apps-network:
    external: true

volumes:
  db_data_soccto: